[settings]
log_level = "DEBUG"
data_file = "data.txt"
max_retries = 3

[database]
host = "localhost"
port = 5432
username = "envvar1"
password = "envvar2"
database_name = "envar3" #in production would use a key and auth solution for these